# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tukituki < Formula
  desc "A terminal UI for managing multiple dev processes"
  homepage "https://github.com/dvaldivia/tukituki"
  version "0.0.6"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/dvaldivia/tukituki/releases/download/v0.0.6/tukituki_darwin_amd64.tar.gz"
      sha256 "db69216b7d7153496d74a909eb7cfb1fe882eaf59417a562f7a70ae6cdd9c7c0"

      define_method(:install) do
        bin.install "tukituki"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/dvaldivia/tukituki/releases/download/v0.0.6/tukituki_darwin_arm64.tar.gz"
      sha256 "0a5a938ddca73591d604576b77e29b31e20d27671d6bb740c490010ca8c82689"

      define_method(:install) do
        bin.install "tukituki"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/dvaldivia/tukituki/releases/download/v0.0.6/tukituki_linux_amd64.tar.gz"
      sha256 "62a80e5245a4652767f4fb4b782d62838bd0c7e7b2d73e89930784a3fb877a66"
      define_method(:install) do
        bin.install "tukituki"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dvaldivia/tukituki/releases/download/v0.0.6/tukituki_linux_arm64.tar.gz"
      sha256 "a4e136e4666728e6e3afbfd7e7374951adcc99381f63acf3ae792b227b58a5d5"
      define_method(:install) do
        bin.install "tukituki"
      end
    end
  end

  test do
    system "#{bin}/tukituki", "--version"
  end
end
